module.exports = {
  MONGO_CONNECTION_STRING: process.env.MONGO_CONNECTION_STRING,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_FRONT_KEY: process.env.STRIPE_FRONT_KEY,
  EXPRESS_SECRET_KEY: process.env.EXPRESS_SECRET_KEY,
  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
  BASE_URL: process.env.BASE_URL,
};
