export const USER_LOGOUT = "USER_LOGOUT";
export const FETCH_HOME_IMAGES = "FETCH_HOME_IMAGES";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const FETCH_OWN_IMAGES_FOR_SALE = "FETCH_OWN_IMAGES_FOR_SALE";
export const FETCH_OWN_IMAGES_NOT_FOR_SALE = "FETCH_OWN_IMAGES_NOT_FOR_SALE";
export const FETCH_PURCHASE_HISTORY = "FETCH_PURCHASE_HISTORY";
export const FETCH_IMAGES_BY_SEARCH = "FETCH_IMAGES_BY_SEARCH";
export const ADD_CREDITS = "ADD_CREDITS";

// Other types
export const OWN_IMAGES = {
  QUERY_TYPE_NOT_FOR_SALE: "QUERY_TYPE_NOT_FOR_SALE",
  QUERY_TYPE_FOR_SALE: "QUERY_TYPE_FOR_SALE",
};
export const CHILD_OVERLAY = "child-overlay";
export const PARENT_OVERLAY = "parent-overlay";
